export const NAVIGATIONS_ROUTE = {
    SCREEN_LOGIN : 'LoginScreen',
    SCREEN_REGISTER : 'RegisterScreen',
    SCREEN_OTP : 'OtpScreen',
    SCREEN_NEW_PASSWORD : 'NewPasswordScreen',
    SCREEN_FORGET_PASSWORD : 'ForgetPasswordScreen',
    SCREEN_CHANGE_PASSWORD : 'ChangePasswordScreen',
    SCREEN_HOME : 'HomeScreen',
    SCREEN_CHARGING: 'ChargingStation',
    SCREEN_PROFILE: 'ProfileScreen',
    SCREEN_USER: 'UserScreen',
    ROOT_STACK : 'RootStack',
    SCREEN_STATUS_STATION: 'StatusStation',
    SCREEN_BOOKING_SELECTION: 'SelectionBooking',
    SCREEN_CHARGING_CAR: 'ChargingScreen',
    SCREEN_PAYMENT: 'PaymentScreen',
    BOTTOM_NAVIGATION: 'BottomNavigation',
    SCREEN_HISTORY_CHARGING: 'ChargingHistory',
    SCREEN_DRAWER: 'DrawerNavigation',
    SCREEN_USERLIST: 'UserListScreen',
    SCREEN_CHARGER_MANAGEMENT: 'ChargeManagement',
    SCREEN_ADD_STATION: 'AddStationScreen',
    SCREEN_EDIT_STATION: 'EditStationScreen',
    SCREEN_SEARCH_STATION: 'SearchChargingStation',
    SCREEN_DETAIL_STATION: 'DetailStationScreen',
    SCREEN_CHARGING_CODE: 'ChargingCodeScreen',
    SCREEN_VNPAY: 'VnpayScreen',
    SCREEN_PAYMENT_RESULT: 'PaymentResultScreen',
    SCREEN_PAYMENT_FAIL: 'PaymentFailScreen',
    SCREEN_SPLASH: 'SplashScreen',
    SCREEN_QRSCAN: 'QRCodeScannerScreen',
    SCREEN_NOTIFICATION: 'NotificationScreen',
    SCREEN_SETTING: 'SettingScreen',
    SCREEN_POLICY: 'PolicyScreen',
    SCREEN_SUPPORT: 'SupportScreen',
    
};